name: CMake

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [ "clang", "gcc" ]

    steps:
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenal-dev libalut-dev libserialport-dev libzstd-dev libcjson-dev

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=${{matrix.compiler}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: CTest
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{matrix.compiler}}-bin
          path: |
            build/fplayer
            build/mftool

  Windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          pacboy: >-
            gcc:p
            cmake:p
            ninja:p
            zstd:p
            openal:p
            freealut:p
            libserialport:p
            winpthreads:p
            cjson:p

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

      - name: Build
        run: cmake --build build

      - name: CTest
        working-directory: ${{github.workspace}}\build
        run: ctest -C ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: |
            build\fplayer.exe
            build\mftool.exe

  macOS:
    runs-on: macos-latest

    steps:
      - name: Install libraries
        run: |
          brew update
          brew install libserialport freealut zstd cjson

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=$(brew --prefix)

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: CTest
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v4
        with:
          name: macos-bin
          path: |
            build/fplayer
            build/mftool
