name: Fuzz

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenal-dev libalut-dev libserialport-dev libzstd-dev

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang -DENABLE_FUZZING=TRUE

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: fuzz_cmap_parse_csv_line
        working-directory: ${{github.workspace}}/build
        run: |
          mkdir -p corpus/cmap_parse_csv_line
          ./fuzz_cmap_parse_csv_line -max_len=16 -max_total_time=30 -print_final_stats=1 -close_fd_mask=2 -dict=../fuzz/cmap.dict corpus/cmap_parse_csv_line

      - name: fuzz_cmap_parse_csv
        working-directory: ${{github.workspace}}/build
        run: |
          mkdir -p corpus/fuzz_cmap_parse_csv
          ./fuzz_cmap_parse_csv -max_len=16 -max_total_time=30 -print_final_stats=1 -close_fd_mask=2 -dict=../fuzz/cmap.dict corpus/fuzz_cmap_parse_csv

      - uses: actions/upload-artifact@v3
        with:
          name: corpus.zip
          path: ${{github.workspace}}/build/corpus
