name: UBSan

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenal-dev libalut-dev libserialport-dev libzstd-dev libcjson-dev

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang -DUSE_UBSAN=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: CTest
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Test help menu
        run: |
          ./build/fplayer -h

      - name: Test serial port list
        run: |
          ./build/fplayer -l

      - name: Test channel map
        run: |
          ./build/fplayer -t channels.json

      - name: Generate test sequences
        run: |
          for fps in 25 40 60 120
          do
            ./build/gentool -o test_${fps}fps_compressed.fseq -f ${fps} -d 300
            ./build/gentool -o test_${fps}fps.fseq -f ${fps} -d 300 -b 0
          done

      - name: Test variable editing
        run: |
          # set variable, print full tables after to prove changes
          ./build/mftool test_25fps.fseq
          ./build/mftool test_25fps.fseq "test_variable.mp3"
          ./build/mftool test_25fps.fseq.orig
          ./build/mftool test_25fps.fseq
          
          # restore original/unmodified version
          mv test_25fps.fseq.orig test_25fps.fseq
          ./build/mftool test_25fps.fseq

      - name: Run generated sequences (compressed)
        run: |
          for fps in 25 40 60 120
          do
            ./build/fplayer -f test_${fps}fps_compressed.fseq -c channels.json
          done

      - name: Run generated sequences (decompressed)
        run: |
          for fps in 25 40 60 120
          do
            ./build/fplayer -f test_${fps}fps.fseq -c channels.json
          done
