name: Valgrind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libserialport-dev libzstd-dev

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_OPENAL=NO

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: CTest
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Install valgrind
        run: sudo apt-get install -y valgrind

      - name: Test channel map
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -t channels.csv

      - name: Run generated sequences
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -f test/5fps_10s.fseq -c channels.csv
          valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -f test/25fps_10s.fseq -c channels.csv
          valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -f test/40fps_10s.fseq -c channels.csv
          valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -f test/60fps_10s.fseq -c channels.csv
          valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -f test/1000fps_10s.fseq -c channels.csv
