name: Valgrind

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenal-dev libalut-dev libserialport-dev libzstd-dev valgrind

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_OPENAL=NO

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: CTest
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Test channel map
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -t channels.csv

      - name: Generate test sequences
        run: |
          for fps in 25 40 60 120
          do
            valgrind --leak-check=full --error-exitcode=1 ./build/gentool -o test_${fps}fps_compressed.fseq -f ${fps} -d 300
            valgrind --leak-check=full --error-exitcode=1 ./build/gentool -o test_${fps}fps.fseq -f ${fps} -d 300 -b 0
          done

      - name: Test variable editing
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./build/mftool test_25fps.fseq
          valgrind --leak-check=full --error-exitcode=1 ./build/mftool test_25fps.fseq "test_variable.mp3"
          valgrind --leak-check=full --error-exitcode=1 ./build/mftool test_25fps.fseq.orig
          valgrind --leak-check=full --error-exitcode=1 ./build/mftool test_25fps.fseq

      - name: Run generated sequences (compressed)
        run: |
          for fps in 25 40 60 120
          do
            # run without precompute enabled
            valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -f test_${fps}fps_compressed.fseq -c channels.csv
          
            # run with precompute calculated at runtime, data is saved for next run
            valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -p -f test_${fps}fps_compressed.fseq -c channels.csv
          
            # run with precompute loaded from cache file
            valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -p -f test_${fps}fps_compressed.fseq -c channels.csv
          done

      - name: Run generated sequences (decompressed)
        run: |
          for fps in 25 40 60 120
          do
            # run without precompute enabled
            valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -f test_${fps}fps.fseq -c channels.csv
          
            # run with precompute calculated at runtime, data is saved for next run
            valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -p -f test_${fps}fps.fseq -c channels.csv
          
            # run with precompute loaded from cache file
            valgrind --leak-check=full --error-exitcode=1 ./build/fplayer -p -f test_${fps}fps.fseq -c channels.csv
          done
